### ISSUE TITLE
Debian 11 : gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

### ISSUE THREAD

**Issue by buxx** [emirror-de/libayatana-appindicator-rs#2]
Hello,
Example fail with Debian 11 : 

```
sudo apt-get install libayatana-appindicator3-dev git
git clone https://github.com/emirror-de/libayatana-appindicator-rs.git
cd libayatana-appindicator-rs
cargo run --example hello-rust
[ ...]
(hello-rust:6623): Gtk-CRITICAL **: 03:23:12.996: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

And no tray icon appear.

**Comment by emirror-de** [comment]
Hi there,
thanks for your report!

What desktop environment are you using? (If GNOME, what extensions do you have installed?)

Edit: And which version?

**Comment by buxx** [comment]
Hello @emirror-de ,

Tested on a fresh Debian 11 installation in Virtual machine : 

```
osboxes@osboxes:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

```
osboxes@osboxes:~$ cargo --version
cargo 1.63.0 (fd9c4297c 2022-07-01)
osboxes@osboxes:~$ rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

```
$ sudo apt-cache policy libayatana-appindicator3-1 
libayatana-appindicator3-1:
  Installé : 0.5.5-2
  Candidat : 0.5.5-2
 Table de version :
 *** 0.5.5-2 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
$ sudo apt-cache policy libayatana-appindicator3-dev 
libayatana-appindicator3-dev:
  Installé : 0.5.5-2
  Candidat : 0.5.5-2
 Table de version :
 *** 0.5.5-2 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
osboxes@osboxes:~$ sudo apt-cache policy gnome
gnome:
  Installed: 1:3.38+3
  Candidate: 1:3.38+3
  Version table:
 *** 1:3.38+3 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

![VirtualBox_D11_18_08_2022_10_17_55](https://user-images.githubusercontent.com/1104637/185346119-559123b1-39a3-4ae8-84ce-607ff2cb5366.png)

**Comment by emirror-de** [comment]
Thanks for this detailed information. Since GNOME has dropped tray support quite a some time ago, you need to install an extension to enable tray support again.

Some examples:
https://extensions.gnome.org/extension/615/appindicator-support/
https://extensions.gnome.org/extension/2890/tray-icons-reloaded/

Please try again with one of these extensions enabled. If the problem persists, I am happy to have a look and reproduce it this weekend.

**Comment by buxx** [comment]
@emirror-de Working with https://extensions.gnome.org/extension/615/appindicator-support/ installed ! :heart:
